// @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
// Surface `delta` from schemas/delta.json, model sha256:cf7dfa4e63bdb67441babc61f7e861b18cb1a9d822ca8e6b8757d66ce943b5e7.
// Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.

package io.github.lazily

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject

private fun deltaWireFail(message: String): Nothing = throw IpcDecodeException.Malformed(message)

private fun deltaWireObject(
    name: String,
    value: JsonElement,
    required: List<String>,
    optional: List<String>,
): JsonObject {
    val obj = value as? JsonObject ?: deltaWireFail("$name: expected an object, got $value")
    val missing = required.firstOrNull { it !in obj }
    if (missing != null) deltaWireFail("$name: missing field \"$missing\"")
    val unknown = obj.keys.filter { it !in required && it !in optional }.minOrNull()
    if (unknown != null) deltaWireFail("$name: unknown field \"$unknown\"")
    return obj
}

private fun deltaWireTag(
    name: String,
    value: JsonElement,
): Map.Entry<String, JsonElement> {
    val obj = value as? JsonObject ?: deltaWireFail("$name: expected a single-key object, got $value")
    if (obj.size != 1) deltaWireFail("$name: expected exactly one variant tag, got ${obj.keys.sorted()}")
    return obj.entries.single()
}

private fun deltaWireString(
    name: String,
    value: JsonElement,
): String {
    val primitive = value as? JsonPrimitive
    if (primitive == null || !primitive.isString) deltaWireFail("$name: expected a string, got $value")
    return primitive.content
}

private val deltaWireU64Literal = Regex("0|[1-9][0-9]*")

/** The text of a bare unsigned integer literal: no sign, fraction, exponent, leading zero or quotes. */
private fun deltaWireUnsigned(value: JsonElement): String? =
    (value as? JsonPrimitive)?.takeUnless { it.isString }?.content?.takeIf { deltaWireU64Literal.matches(it) }

/**
 * Decode a u64 into a signed `Long`. A value past 2^63-1 is refused rather than
 * wrapped: a binding that cannot represent a wire value exactly must reject the
 * frame (protocol.md § NodeId / PeerId).
 */
private fun deltaWireLong(
    name: String,
    value: JsonElement,
): Long {
    val literal = deltaWireUnsigned(value) ?: deltaWireFail("$name: expected an unsigned integer, got $value")
    return literal.toLongOrNull() ?: deltaWireFail("$name: $literal exceeds this binding's range 0..=2^63-1")
}

/** Encode a `Long` as a u64, refusing a negative value. */
private fun deltaWireLongJson(
    name: String,
    value: Long,
): JsonPrimitive {
    require(value >= 0) { "$name: $value is negative; the wire type is u64" }
    return JsonPrimitive(value)
}

/** Decode serialized bytes from a JSON array of u8 (never base64). */
private fun deltaWireBytes(
    name: String,
    value: JsonElement,
): ByteArray {
    val items = value as? JsonArray ?: deltaWireFail("$name: expected an array of bytes, got $value")
    val out = ByteArray(items.size)
    for (i in items.indices) {
        val byte = deltaWireUnsigned(items[i])?.toIntOrNull()
        if (byte == null || byte > 255) deltaWireFail("$name: expected an array of bytes (0..=255), got $value")
        out[i] = byte.toByte()
    }
    return out
}

/** Encode bytes as a JSON array of u8. */
private fun deltaWireByteArray(bytes: ByteArray): JsonArray {
    val items = ArrayList<JsonPrimitive>(bytes.size)
    for (i in bytes.indices) {
        items.add(JsonPrimitive(bytes[i].toInt() and 0xff))
    }
    return JsonArray(items)
}

private fun deltaWireList(
    name: String,
    value: JsonElement,
): JsonArray = value as? JsonArray ?: deltaWireFail("$name: expected an array, got $value")

/** One incremental graph mutation. Externally tagged: a single-key object whose key is the PascalCase variant name. */
sealed interface DeltaOp {
    /** Encode the externally-tagged wire form. */
    fun toJson(): JsonObject

    /** A source cell was changed to `payload`. */
    data class CellSet(
        /** Target node. */
        val node: NodeId,
        /** Value, inline or by blob descriptor. */
        val payload: IpcValue,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "CellSet",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.CellSet.node", node))
                        put("payload", payload.toJson())
                    },
                )
            }

        companion object
    }

    /** A lazily recomputed slot published a concrete value. */
    data class SlotValue(
        /** Target node. */
        val node: NodeId,
        /** Value, inline or by blob descriptor. */
        val payload: IpcValue,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "SlotValue",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.SlotValue.node", node))
                        put("payload", payload.toJson())
                    },
                )
            }

        companion object
    }

    /** A node was dirtied without publishing a concrete value. */
    data class Invalidate(
        /** Target node. */
        val node: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "Invalidate",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.Invalidate.node", node))
                    },
                )
            }

        companion object
    }

    /** A new node became visible. */
    data class NodeAdd(
        /** New node. */
        val node: NodeId,
        /** Binding-defined type tag of the new node. */
        val typeTag: String,
        /** Initial node body. */
        val state: NodeState,
        /**
         * Optional wire-stable keyed address. A conforming ENCODER omits it when absent; an explicit null is also
         * wire-valid and a decoder MUST read both forms as absent (protocol.md § NodeKey, #lzkeynullstrict). This
         * carried a bare NodeKey $ref until that audit, which made a frame the spec now requires decoders to accept
         * schema-invalid.
         */
        val key: NodeKey? = null,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "NodeAdd",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.NodeAdd.node", node))
                        put("type_tag", JsonPrimitive(typeTag))
                        put("state", state.toJson())
                        if (key != null) put("key", key.toJson())
                    },
                )
            }

        companion object
    }

    /** A node was removed. */
    data class NodeRemove(
        /** Target node. */
        val node: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "NodeRemove",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.NodeRemove.node", node))
                    },
                )
            }

        companion object
    }

    /** A dependency edge was added. */
    data class EdgeAdd(
        /** Node that reads `dependency`. */
        val dependent: NodeId,
        /** Node read by `dependent`. */
        val dependency: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "EdgeAdd",
                    buildJsonObject {
                        put("dependent", deltaWireLongJson("DeltaOp.EdgeAdd.dependent", dependent))
                        put("dependency", deltaWireLongJson("DeltaOp.EdgeAdd.dependency", dependency))
                    },
                )
            }

        companion object
    }

    /** A dependency edge was removed. */
    data class EdgeRemove(
        /** Node that reads `dependency`. */
        val dependent: NodeId,
        /** Node read by `dependent`. */
        val dependency: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "EdgeRemove",
                    buildJsonObject {
                        put("dependent", deltaWireLongJson("DeltaOp.EdgeRemove.dependent", dependent))
                        put("dependency", deltaWireLongJson("DeltaOp.EdgeRemove.dependency", dependency))
                    },
                )
            }

        companion object
    }

    /**
     * Op-log delta form for a QueueCell node: append `payload` to the tail. The op-log delta is the incremental
     * counterpart to the storage-snapshot form (cell-model.md § Wire and snapshot shape); a run of same-direction
     * QueuePush ops fuses into one multi-epoch batch Delta (protocol.md § Backpressure & outbox coalescing).
     */
    data class QueuePush(
        /** Target node. */
        val node: NodeId,
        /** Value, inline or by blob descriptor. */
        val payload: IpcValue,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "QueuePush",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.QueuePush.node", node))
                        put("payload", payload.toJson())
                    },
                )
            }

        companion object
    }

    /**
     * Op-log delta form for a QueueCell node: remove the head. Carries no value (the popped element is determined by
     * ordered replay); a re-delivered pop is Ignored by the epoch gap rule. Crosses the wire only when consumption is
     * authoritatively replicated (mirror sync); in the default producer→consumer sync the remote consumer's pops are
     * local. A QueuePop/QueueClose is a fusion boundary (order-sensitive).
     */
    data class QueuePop(
        /** Target node. */
        val node: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "QueuePop",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.QueuePop.node", node))
                    },
                )
            }

        companion object
    }

    /**
     * Op-log delta form for a QueueCell node: mark closed (idempotent, terminal — Closed is distinct from Empty). A
     * fusion boundary.
     */
    data class QueueClose(
        /** Target node. */
        val node: NodeId,
    ) : DeltaOp {
        override fun toJson(): JsonObject =
            buildJsonObject {
                put(
                    "QueueClose",
                    buildJsonObject {
                        put("node", deltaWireLongJson("DeltaOp.QueueClose.node", node))
                    },
                )
            }

        companion object
    }

    companion object {
        /** Decode strictly: exactly one known variant. */
        fun fromJson(element: JsonElement): DeltaOp {
            val (tag, body) = deltaWireTag("DeltaOp", element)
            return when (tag) {
                "CellSet" -> deltaWireDeltaOpCellSet(body)
                "SlotValue" -> deltaWireDeltaOpSlotValue(body)
                "Invalidate" -> deltaWireDeltaOpInvalidate(body)
                "NodeAdd" -> deltaWireDeltaOpNodeAdd(body)
                "NodeRemove" -> deltaWireDeltaOpNodeRemove(body)
                "EdgeAdd" -> deltaWireDeltaOpEdgeAdd(body)
                "EdgeRemove" -> deltaWireDeltaOpEdgeRemove(body)
                "QueuePush" -> deltaWireDeltaOpQueuePush(body)
                "QueuePop" -> deltaWireDeltaOpQueuePop(body)
                "QueueClose" -> deltaWireDeltaOpQueueClose(body)
                else -> deltaWireFail("DeltaOp: unknown variant \"$tag\"")
            }
        }
    }
}

private fun deltaWireDeltaOpCellSet(body: JsonElement): DeltaOp.CellSet {
    val obj = deltaWireObject("DeltaOp.CellSet", body, listOf("node", "payload"), emptyList())
    return DeltaOp.CellSet(
        node = deltaWireLong("DeltaOp.CellSet.node", obj.getValue("node")),
        payload = IpcValue.fromJson(obj.getValue("payload")),
    )
}

private fun deltaWireDeltaOpSlotValue(body: JsonElement): DeltaOp.SlotValue {
    val obj = deltaWireObject("DeltaOp.SlotValue", body, listOf("node", "payload"), emptyList())
    return DeltaOp.SlotValue(
        node = deltaWireLong("DeltaOp.SlotValue.node", obj.getValue("node")),
        payload = IpcValue.fromJson(obj.getValue("payload")),
    )
}

private fun deltaWireDeltaOpInvalidate(body: JsonElement): DeltaOp.Invalidate {
    val obj = deltaWireObject("DeltaOp.Invalidate", body, listOf("node"), emptyList())
    return DeltaOp.Invalidate(
        node = deltaWireLong("DeltaOp.Invalidate.node", obj.getValue("node")),
    )
}

private fun deltaWireDeltaOpNodeAdd(body: JsonElement): DeltaOp.NodeAdd {
    val obj = deltaWireObject("DeltaOp.NodeAdd", body, listOf("node", "type_tag", "state"), listOf("key"))
    return DeltaOp.NodeAdd(
        node = deltaWireLong("DeltaOp.NodeAdd.node", obj.getValue("node")),
        typeTag = deltaWireString("DeltaOp.NodeAdd.type_tag", obj.getValue("type_tag")),
        state = NodeState.fromJson(obj.getValue("state")),
        key = obj["key"]?.takeUnless { it is JsonNull }?.let { value -> NodeKey.fromJson(value) },
    )
}

private fun deltaWireDeltaOpNodeRemove(body: JsonElement): DeltaOp.NodeRemove {
    val obj = deltaWireObject("DeltaOp.NodeRemove", body, listOf("node"), emptyList())
    return DeltaOp.NodeRemove(
        node = deltaWireLong("DeltaOp.NodeRemove.node", obj.getValue("node")),
    )
}

private fun deltaWireDeltaOpEdgeAdd(body: JsonElement): DeltaOp.EdgeAdd {
    val obj = deltaWireObject("DeltaOp.EdgeAdd", body, listOf("dependent", "dependency"), emptyList())
    return DeltaOp.EdgeAdd(
        dependent = deltaWireLong("DeltaOp.EdgeAdd.dependent", obj.getValue("dependent")),
        dependency = deltaWireLong("DeltaOp.EdgeAdd.dependency", obj.getValue("dependency")),
    )
}

private fun deltaWireDeltaOpEdgeRemove(body: JsonElement): DeltaOp.EdgeRemove {
    val obj = deltaWireObject("DeltaOp.EdgeRemove", body, listOf("dependent", "dependency"), emptyList())
    return DeltaOp.EdgeRemove(
        dependent = deltaWireLong("DeltaOp.EdgeRemove.dependent", obj.getValue("dependent")),
        dependency = deltaWireLong("DeltaOp.EdgeRemove.dependency", obj.getValue("dependency")),
    )
}

private fun deltaWireDeltaOpQueuePush(body: JsonElement): DeltaOp.QueuePush {
    val obj = deltaWireObject("DeltaOp.QueuePush", body, listOf("node", "payload"), emptyList())
    return DeltaOp.QueuePush(
        node = deltaWireLong("DeltaOp.QueuePush.node", obj.getValue("node")),
        payload = IpcValue.fromJson(obj.getValue("payload")),
    )
}

private fun deltaWireDeltaOpQueuePop(body: JsonElement): DeltaOp.QueuePop {
    val obj = deltaWireObject("DeltaOp.QueuePop", body, listOf("node"), emptyList())
    return DeltaOp.QueuePop(
        node = deltaWireLong("DeltaOp.QueuePop.node", obj.getValue("node")),
    )
}

private fun deltaWireDeltaOpQueueClose(body: JsonElement): DeltaOp.QueueClose {
    val obj = deltaWireObject("DeltaOp.QueueClose", body, listOf("node"), emptyList())
    return DeltaOp.QueueClose(
        node = deltaWireLong("DeltaOp.QueueClose.node", obj.getValue("node")),
    )
}

/** Incremental change set: ordered ops that take the receiver from `base_epoch` to `epoch`. */
data class Delta(
    /** Epoch this delta applies to (must equal the receiver's last_epoch). */
    val baseEpoch: Long,
    /**
     * New epoch, >= base_epoch + 1. Usually base_epoch + 1; a multi-epoch-span delta has epoch > base_epoch + 1 (epoch
     * - base_epoch = accepted-event span). See protocol.md § Multi-epoch-span delta.
     */
    val epoch: Long,
    /** Ordered operations. */
    val ops: List<DeltaOp> = emptyList(),
) {
    /** Encode the wire object, omitting an absent optional field. */
    fun toJson(): JsonObject =
        buildJsonObject {
            put("base_epoch", deltaWireLongJson("Delta.base_epoch", baseEpoch))
            put("epoch", deltaWireLongJson("Delta.epoch", epoch))
            put("ops", JsonArray(ops.map { item -> item.toJson() }))
        }

    companion object {
        /** Decode strictly: exactly the declared keys, each well-typed. */
        fun fromJson(element: JsonElement): Delta {
            val obj = deltaWireObject("Delta", element, listOf("base_epoch", "epoch", "ops"), emptyList())
            return Delta(
                baseEpoch = deltaWireLong("Delta.base_epoch", obj.getValue("base_epoch")),
                epoch = deltaWireLong("Delta.epoch", obj.getValue("epoch")),
                ops = deltaWireList("Delta.ops", obj.getValue("ops")).map { item -> DeltaOp.fromJson(item) },
            )
        }
    }
}

/** Externally-tagged delta payload: inline bytes or a shared-memory blob reference. */
sealed interface IpcValue {
    /** Encode the externally-tagged wire form. */
    fun toJson(): JsonObject

    /** Inline serialized bytes as JSON array of u8 (NOT base64). */
    data class Inline(
        val bytes: ByteArray,
    ) : IpcValue {
        override fun toJson(): JsonObject = buildJsonObject { put("Inline", deltaWireByteArray(bytes)) }

        override fun equals(other: Any?): Boolean = other is Inline && bytes.contentEquals(other.bytes)

        override fun hashCode(): Int = bytes.contentHashCode()

        companion object
    }

    /** Value stored in a blob backend, by descriptor. */
    data class SharedBlob(
        val blob: ShmBlobRef,
    ) : IpcValue {
        override fun toJson(): JsonObject = buildJsonObject { put("SharedBlob", blob.toJson()) }

        companion object
    }

    companion object {
        /** Decode strictly: exactly one known variant. */
        fun fromJson(element: JsonElement): IpcValue {
            val (tag, body) = deltaWireTag("IpcValue", element)
            return when (tag) {
                "Inline" -> deltaWireIpcValueInline(body)
                "SharedBlob" -> deltaWireIpcValueSharedBlob(body)
                else -> deltaWireFail("IpcValue: unknown variant \"$tag\"")
            }
        }
    }
}

private fun deltaWireIpcValueInline(body: JsonElement): IpcValue.Inline =
    IpcValue.Inline(deltaWireBytes("IpcValue.Inline", body))

private fun deltaWireIpcValueSharedBlob(body: JsonElement): IpcValue.SharedBlob =
    IpcValue.SharedBlob(ShmBlobRef.fromJson(body))

/**
 * Externally-tagged node body: concrete bytes, a shared-memory value, or an opaque (visible but non-serializable) node.
 */
sealed interface NodeState {
    /** Encode the externally-tagged wire form. */
    fun toJson(): JsonElement

    /** Serialized value bytes as JSON array of u8 (NOT base64). */
    data class Payload(
        val bytes: ByteArray,
    ) : NodeState {
        override fun toJson(): JsonObject = buildJsonObject { put("Payload", deltaWireByteArray(bytes)) }

        override fun equals(other: Any?): Boolean = other is Payload && bytes.contentEquals(other.bytes)

        override fun hashCode(): Int = bytes.contentHashCode()

        companion object
    }

    /** Value stored in a blob backend, by descriptor. */
    data class SharedBlob(
        val blob: ShmBlobRef,
    ) : NodeState {
        override fun toJson(): JsonObject = buildJsonObject { put("SharedBlob", blob.toJson()) }

        companion object
    }

    /** Visible but non-serializable node: no body crosses the wire. */
    data object Opaque : NodeState {
        override fun toJson(): JsonElement = JsonPrimitive("Opaque")
    }

    companion object {
        /** Decode strictly: exactly one known variant. */
        fun fromJson(element: JsonElement): NodeState {
            if (element is JsonPrimitive && element.isString) {
                return when (val unit = element.content) {
                    "Opaque" -> Opaque
                    else -> deltaWireFail("NodeState: unknown unit variant \"$unit\"")
                }
            }
            val (tag, body) = deltaWireTag("NodeState", element)
            return when (tag) {
                "Payload" -> deltaWireNodeStatePayload(body)
                "SharedBlob" -> deltaWireNodeStateSharedBlob(body)
                else -> deltaWireFail("NodeState: unknown variant \"$tag\"")
            }
        }
    }
}

private fun deltaWireNodeStatePayload(body: JsonElement): NodeState.Payload =
    NodeState.Payload(deltaWireBytes("NodeState.Payload", body))

private fun deltaWireNodeStateSharedBlob(body: JsonElement): NodeState.SharedBlob =
    NodeState.SharedBlob(ShmBlobRef.fromJson(body))
