// @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
// Surface `receipts` from schemas/receipts.json, model sha256:faf31f5c1db054295114b513d51ae6d4b7b47658147cf8044838340a72946b87.
// Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.
@file:OptIn(ExperimentalSerializationApi::class)

package io.github.lazily

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject

private fun receiptsWireObject(
    name: String,
    value: JsonElement,
    fields: List<String>,
): JsonObject {
    val obj = value as? JsonObject ?: throw IllegalArgumentException("$name: expected an object, got $value")
    fields.firstOrNull { it !in obj }?.let { throw IllegalArgumentException("$name: missing field \"$it\"") }
    obj.keys.filter { it !in fields }.minOrNull()?.let { throw IllegalArgumentException("$name: unknown field \"$it\"") }
    return obj
}

private fun receiptsWireString(
    name: String,
    value: JsonElement,
): String {
    val primitive = value as? JsonPrimitive
    if (primitive == null || !primitive.isString) {
        throw IllegalArgumentException("$name: expected a string, got $value")
    }
    return primitive.content
}

private val receiptsWireU64Literal = Regex("0|[1-9][0-9]*")

private fun receiptsWireU64(
    name: String,
    value: JsonElement,
): ULong {
    val primitive = value as? JsonPrimitive
    val literal = primitive?.takeUnless { it.isString }?.content
    return literal?.takeIf { receiptsWireU64Literal.matches(it) }?.toULongOrNull()
        ?: throw IllegalArgumentException("$name: expected an unsigned integer, got $value")
}

private fun receiptsWireList(
    name: String,
    value: JsonElement,
): JsonArray = value as? JsonArray ?: throw IllegalArgumentException("$name: expected an array, got $value")

/** Outcome vocabulary. observed/accepted are non-terminal; applied/rejected are terminal. */
enum class ReceiptOutcome(
    val wireName: String,
) {
    /** A peer/process observed the causation request. */
    Observed("observed"),

    /** A peer/process accepted or queued the request. */
    Accepted("accepted"),

    /** The requested effect/state change was applied. */
    Applied("applied"),

    /** The requested effect/state change was rejected. */
    Rejected("rejected"),
    ;

    companion object {
        /** Parse a wire string, rejecting unknown values. */
        fun fromWire(value: String): ReceiptOutcome =
            entries.firstOrNull { it.wireName == value }
                ?: throw IllegalArgumentException("unknown ReceiptOutcome: \"$value\"")
    }
}

/** One receipt event for a command/effect causation id. */
data class CausalReceipt(
    /** Idempotency key for this receipt event. */
    val receiptId: String,
    /** Stable id of the command, event, or effect request this receipt observes. */
    val causationId: String,
    /** Peer, process, or subsystem that produced the receipt. */
    val observer: String,
    /** Producer/editor generation. Consumers discard receipts outside the current generation for the causation id. */
    val generation: ULong,
    /** Receipt outcome. */
    val outcome: ReceiptOutcome,
    /** Optional human/debug rejection reason. */
    val reason: String? = null,
    /** Optional hash of the state/payload observed by the receipt. */
    val payloadHash: String? = null,
) {
    init {
        require(receiptId.length >= 1) { "receipt_id must be a non-empty string" }
        require(causationId.length >= 1) { "causation_id must be a non-empty string" }
        require(observer.length >= 1) { "observer must be a non-empty string" }
    }

    /** Encode the wire object; every declared key is emitted, `null` when absent. */
    fun toJson(): JsonObject =
        buildJsonObject {
            put("receipt_id", JsonPrimitive(receiptId))
            put("causation_id", JsonPrimitive(causationId))
            put("observer", JsonPrimitive(observer))
            put("generation", JsonPrimitive(generation))
            put("outcome", JsonPrimitive(outcome.wireName))
            put("reason", reason?.let { JsonPrimitive(it) } ?: JsonNull)
            put("payload_hash", payloadHash?.let { JsonPrimitive(it) } ?: JsonNull)
        }

    companion object {
        private val FIELDS = listOf("receipt_id", "causation_id", "observer", "generation", "outcome", "reason", "payload_hash")

        /** Decode strictly: exactly the declared keys, each well-typed. */
        fun fromJson(element: JsonElement): CausalReceipt {
            val obj = receiptsWireObject("CausalReceipt", element, FIELDS)
            return CausalReceipt(
                receiptId = receiptsWireString("CausalReceipt.receipt_id", obj.getValue("receipt_id")),
                causationId = receiptsWireString("CausalReceipt.causation_id", obj.getValue("causation_id")),
                observer = receiptsWireString("CausalReceipt.observer", obj.getValue("observer")),
                generation = receiptsWireU64("CausalReceipt.generation", obj.getValue("generation")),
                outcome = ReceiptOutcome.fromWire(receiptsWireString("CausalReceipt.outcome", obj.getValue("outcome"))),
                reason = obj.getValue("reason").let { value -> if (value is JsonNull) null else receiptsWireString("CausalReceipt.reason", value) },
                payloadHash = obj.getValue("payload_hash").let { value -> if (value is JsonNull) null else receiptsWireString("CausalReceipt.payload_hash", value) },
            )
        }
    }
}

/** Wire body for the externally-tagged `CausalReceipts` envelope. */
data class CausalReceipts(
    /** Receipt batch. */
    val receipts: List<CausalReceipt> = emptyList(),
) {
    /** Encode the wire object; every declared key is emitted, `null` when absent. */
    fun toJson(): JsonObject =
        buildJsonObject {
            put("receipts", JsonArray(receipts.map { item -> item.toJson() }))
        }

    companion object {
        private val FIELDS = listOf("receipts")

        /** Decode strictly: exactly the declared keys, each well-typed. */
        fun fromJson(element: JsonElement): CausalReceipts {
            val obj = receiptsWireObject("CausalReceipts", element, FIELDS)
            return CausalReceipts(
                receipts = receiptsWireList("CausalReceipts.receipts", obj.getValue("receipts")).map { item -> CausalReceipt.fromJson(item) },
            )
        }
    }
}

/** Externally-tagged receipt wire message. */
sealed interface ReceiptMessage {
    /** Encode the externally-tagged wire object. */
    fun toJson(): JsonObject

    /** Encode this message as compact JSON bytes. */
    fun encodeJson(): ByteArray = toJson().toString().encodeToByteArray()

    /** `CausalReceipts` envelope variant. */
    data class CausalReceiptsMessage(
        val batch: CausalReceipts,
    ) : ReceiptMessage {
        override fun toJson(): JsonObject = buildJsonObject { put("CausalReceipts", batch.toJson()) }
    }

    companion object {
        /** Decode JSON bytes strictly. */
        fun decodeJson(data: ByteArray): ReceiptMessage = decodeJson(data.decodeToString())

        /** Decode a JSON string strictly. */
        fun decodeJson(data: String): ReceiptMessage = fromJson(Json.parseToJsonElement(data))

        /** Decode strictly: exactly one known variant tag. */
        fun fromJson(element: JsonElement): ReceiptMessage {
            val obj = element as? JsonObject ?: throw IllegalArgumentException("ReceiptMessage: expected an object, got $element")
            require(obj.size == 1) { "ReceiptMessage: expected exactly one variant tag, got ${obj.keys.sorted()}" }
            val (tag, body) = obj.entries.single()
            return when (tag) {
                "CausalReceipts" -> CausalReceiptsMessage(CausalReceipts.fromJson(body))
                else -> throw IllegalArgumentException("ReceiptMessage: unknown variant \"$tag\"")
            }
        }
    }
}
